[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
build_flags =
    -std=gnu++17
    -O2
    -DNDEBUG
    -DEIGEN_NO_DEBUG
    -DEIGEN_DONT_VECTORIZE
    -D_USE_MATH_DEFINES
    -I${PROJECT_DIR}/include
    -IC:/Users/conor/eigen
build_unflags = -std=gnu++11

[platformio]
src_dir = .